Josh
mmnn11/Zumwalt pull request #9
Opened 2017-12-26 01:46 UTC by JoshuaJoost

Issue #2 ready to update

2017-12-28 19:20 UTC, MaxGranzow requested changes
Alles in allem ist das sehr gut und auch ästhetisch ansprechend! :smile:
Im Anschluss habe ich noch ein paar Verbesserungsvorschläge aufgeführt:

- vor dem mergen in den "master" die "Hilfslinen" entfernen (evtl debug-klassen belassen?)
- beim zufälligen Setzen die Anzahl der verbleibenden Schiffe aktualisieren / auf "0" setzen
  + Schaltfläche für "Weiter" aktivieren
- Auskommentierten Code in index.html entfernen bevor merge in "master" (Z.84 - Z.94)
- Vorschlag: 
	'<div id="otherShips" class="col-xs-12 col-md-6 board" hidden>Schiffe des Gegners:</div>'
  einfügen um später einfacher das Spielfeld des Gegners anzuzeigen. Der "Schiffe setzen" Bereich
  wird dann mit "hidden" verborgen.
- main.js: Die leere CSS-Klasse "boardRow" muss nicht extra deklariert werden, sondern kann auch
  implizit verwendet werden.
- in main.js setzt du sehr häufig die "background-color" Eigenschaft auf immer den gleichen Wert
  -> Ziehe eine eigene CSS-Klasse in Betracht
- main.js: Funktion "getRowAndColFromString()", Zeile 144: Man könnte str.split("-") verwenden
  um die Funktion zu vereinfachen.
- main.js Zeile 213: Kein alert() mit debug-informationen an den Nutzer
  -> Evtl eine "Debug-Variable" einführen, die man dann im Produktivsystem auf "false" setzen kann,
  die entscheidet, ob die Debug-Informationen ausgegeben werden.
- main.js: findIndexValueInArray: Es gibt eine Funktion "array.indexOf(element)"
- main.js: Zeile 2 & 3: Nicht Hexcode und rgb-Farben mischen -> Einheitlich machen
  Evtl. Kommentar mit textueller Farbangabe ergänzen
- ships.js: Kommentar ab Zeile 22 weglassen, bzw. durch ein "How-To-Use"-Beispiel als Kommentar ergänzen
- ships.js: Eventuell kann man ES6 Klassen verwenden

- Die Anzahl der verbleibenden Schiffe gefällt mir sehr! :+1:

2017-12-28 19:21 UTC, ModuloGames commented
Bei Vorschlag ist mein HTML verschwunden :rofl:

2017-12-28 21:06 UTC, ModuloGames commented
:bug: Wenn man die Größe des Spielfeldes ändert sind die Felder nicht mehr quadratisch.

2017-12-29 00:35 UTC, JoshuaJoost commented
Danke fürs Feedback, setze mich heute gleich mal ran.

2018-01-05 14:52 UTC, MaxGranzow approved these changes

2018-01-05 14:53 UTC, merged